### PR TITLE
Enhance SimpleSeqPlay

### PR DESCRIPTION
**Pull request by jmirabel**
@nim65s can this be released in 2.3.1 ?

### CODE REVIEW

**Comment by nim65s** [comment]
sure

**Comment by nim65s** [comment]
It would be great to have a simple unit test for this

**Comment by jmirabel** [comment]
The penultimate commit should do the job.

**Comment by jmirabel** [comment]
I added a commit. If this can go in the next release, that would be wonderful. Otherwise, I will find a workaround.

**Comment by nim65s** [comment]
Merged manually

**Pull request closed without merging**
